name: course_home_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            zacharywin/course_home:latest
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SECRET }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            sudo docker pull zacharywin/course_home
            sudo docker stop course_home
            sudo docker rm course_home
            sudo docker run -itd -p 7001:7001 --name=course_home --restart=always -v ~/prod/course_home/temp:/app/temp -v ~/prod/course_home/template:/app/template zacharywin/course_home

